SELECT CAR_ID, ROUND(SUM(DIFF) / COUNT(DIFF), 1) AS AVERAGE_DURATION
FROM (
    SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS CAR_TABLE
GROUP BY CAR_ID
HAVING ROUND(SUM(DIFF) / COUNT(DIFF), 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC