# SELECT J.FLAVOR, J.TOTAL_ORDER
# FROM JULY AS J
# WHERE J.FLAVOR IN
# (SELECT F.FLAVOR
#  FROM FIRST_HALF AS F
# )
SELECT H.FLAVOR AS FLAVOR
FROM JULY AS J
JOIN FIRST_HALF AS H
ON J.FLAVOR = H.FLAVOR
GROUP BY H.FLAVOR
ORDER BY (SUM(J.TOTAL_ORDER) + H.TOTAL_ORDER) DESC
LIMIT 3